all:
	mkdir -p IFAM
	python ./scripts/to_IFAM.py ./raw/A01_6088570/ > IFAM/A_01.json
	#same as A_01: python ./scripts/to_IFAM.py ./raw/A02_6088570/ > IFAM/A_02.json
	#same as A_01: python ./scripts/to_IFAM.py ./raw/A03_6088570/ > IFAM/A_03.json
	#same as A_01: python ./scripts/to_IFAM.py ./raw/A04_6088570/ > IFAM/A_04.json
	python ./scripts/to_IFAM.py ./raw/A05_6088570/ > IFAM/A_05.json
	python ./scripts/to_IFAM.py ./raw/A06_6088590/ > IFAM/A_06.json
	#same as A_06: python ./scripts/to_IFAM.py ./raw/A07_6088590/ > IFAM/A_07.json
	#same as A_06: python ./scripts/to_IFAM.py ./raw/A08_6088590/ > IFAM/A_08.json
	#same as A_06: python ./scripts/to_IFAM.py ./raw/A09_6088590/ > IFAM/A_09.json
	python ./scripts/to_IFAM.py ./raw/A10_6088590/ > IFAM/A_10.json
	python ./scripts/to_IFAM.py ./raw/B_01/        > IFAM/B_01.json
	#same as B_01: python ./scripts/to_IFAM.py ./raw/B_02/        > IFAM/B_02.json
	#same as B_01: python ./scripts/to_IFAM.py ./raw/B_03/        > IFAM/B_03.json
	#same as B_01: python ./scripts/to_IFAM.py ./raw/B_04/        > IFAM/B_04.json
	#same as B_01: python ./scripts/to_IFAM.py ./raw/B_05/        > IFAM/B_05.json
	python ./scripts/to_IFAM.py ./raw/B_06/        > IFAM/B_06.json
	#same as B_06: python ./scripts/to_IFAM.py ./raw/B_07/        > IFAM/B_07.json
	#same as B_06: python ./scripts/to_IFAM.py ./raw/B_08/        > IFAM/B_08.json
	#same as B_06: python ./scripts/to_IFAM.py ./raw/B_09/        > IFAM/B_09.json
	#same as B_06: python ./scripts/to_IFAM.py ./raw/B_10/        > IFAM/B_10.json
	python ./scripts/to_IFAM.py ./raw/X01_DATA/    > IFAM/X_01.json
	#same as X_01: python ./scripts/to_IFAM.py ./raw/X02_DATA/    > IFAM/X_02.json
	python ./scripts/to_IFAM.py ./raw/X03_DATA/    > IFAM/X_03.json
	#same as X_03: python ./scripts/to_IFAM.py ./raw/X04_DATA/    > IFAM/X_04.json
	#same as A_01: python ./scripts/to_IFAM.py ./raw/XA01_DATA/   > IFAM/XA01.json
	#same as A_05: python ./scripts/to_IFAM.py ./raw/XA02_DATA/   > IFAM/XA02.json
	#same as A_06: python ./scripts/to_IFAM.py ./raw/XA03_DATA/   > IFAM/XA03.json
	#same as A_10: python ./scripts/to_IFAM.py ./raw/XA04_DATA/   > IFAM/XA04.json
	#same as B_01: python ./scripts/to_IFAM.py ./raw/XB01_DATA/   > IFAM/XB01.json
	#same as B_01: python ./scripts/to_IFAM.py ./raw/XB02_DATA/   > IFAM/XB02.json
	#same as B_06: python ./scripts/to_IFAM.py ./raw/XB03_DATA/   > IFAM/XB03.json
	#same as B_06: python ./scripts/to_IFAM.py ./raw/XB04_DATA/   > IFAM/XB04.json

